todo_list_mate/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("todo_servise.urls", namespace="todo_servise")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
]

todo_servise/urls.py
from django.urls import path

from todo_servise.views import TodoListView, TaskCreatedView, switch_done_or_not_done, TaskUpdateView, TaskDeleteView, \
    TagListView, TagCreatedView, TagUpdateView, TagDeleteView

urlpatterns = [
    path("", TodoListView.as_view(), name="todo-list"),
    path("task_created/", TaskCreatedView.as_view(), name="task-created"),
    path("task_done_or_not/<int:pk>/", switch_done_or_not_done, name="task-done-or-not"),
    path("update_task/<int:pk>/", TaskUpdateView.as_view(), name="task-update"),
    path("delete_task/<int:pk>/", TaskDeleteView.as_view(), name="task-delete"),
    path("tags/", TagListView.as_view(), name="tag-list"),
    path("tag_create/", TagCreatedView.as_view(), name="tag-create"),
    path("tag_update/<int:pk>/", TagUpdateView.as_view(), name="tag-update"),
    path("tag_delete/<int:pk>/", TagDeleteView.as_view(), name="tag-delete"),

]

app_name = "todo_servise"

todo_servise/models.py
from django.db import models


class Tag(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class Task(models.Model):
    content = models.TextField()
    datetime = models.DateTimeField(auto_now_add=True)
    ded_line = models.DateTimeField(null=True, blank=True)
    done = models.BooleanField(default=False)
    tags = models.ManyToManyField(Tag, related_name='tags')

    class Meta:
        ordering = ["done", '-datetime']

    def __str__(self):
        task_tags = self.tags.all()

        tag_names = ", ".join([tag.name for tag in task_tags])
        return f"{self.content}: {tag_names} ({self.done})"

todo_servise/forms.py
from django import forms
from django.forms import DateTimeInput

from todo_servise.models import Task, Tag


class TaskForm(forms.ModelForm):
    tags = forms.ModelMultipleChoiceField(
        queryset=Tag.objects.all(),
        widget=forms.CheckboxSelectMultiple(),
    )
    class Meta:
        model = Task
        fields = "__all__"
        widgets = {
            "ded_line": DateTimeInput(
                attrs={"type": "datetime-local"}
            ),
        }

todo_servise/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpRequest, HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic

from todo_servise.forms import TaskForm
from todo_servise.models import Task, Tag


class TodoListView(LoginRequiredMixin, generic.ListView):
    model = Task
    template_name = "todo_servise/todo_list.html"
    context_object_name = "task_list"


class TaskCreatedView(LoginRequiredMixin, generic.edit.CreateView):
    model = Task
    form_class = TaskForm
    success_url = reverse_lazy("todo_servise:todo-list")


class TaskUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Task
    form_class = TaskForm
    success_url = reverse_lazy("todo_servise:todo-list")


class TaskDeleteView(LoginRequiredMixin, generic.edit.DeleteView):
    model = Task
    success_url = reverse_lazy("todo_servise:todo-list")


@login_required
def switch_done_or_not_done(request, pk):
    task = Task.objects.get(pk=pk)
    if task.done:
        task.done = False
    else:
        task.done = True
    task.save()
    return HttpResponseRedirect(reverse_lazy("todo_servise:todo-list"))


class TagListView(LoginRequiredMixin, generic.ListView):
    model = Tag
    context_object_name = "tag_list"
    template_name = "todo_servise/tag_list.html"


class TagCreatedView(LoginRequiredMixin, generic.edit.CreateView):
    model = Tag
    fields = "__all__"
    success_url = reverse_lazy("todo_servise:tag-list")


class TagUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Tag
    fields = "__all__"
    success_url = reverse_lazy("todo_servise:tag-list")


class TagDeleteView(LoginRequiredMixin, generic.edit.DeleteView):
    model = Tag
    success_url = reverse_lazy("todo_servise:tag-list")

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% block title %}<title>Todo Service</title>{% endblock %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
          integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2"
          crossorigin="anonymous">
    <!-- Add additional CSS in static file -->
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>

<body>
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-2">

            {% block sidebar %}
                {% include "includes/sidebar.html" %}
            {% endblock %}

        </div>
        <div class="col-sm-10 ">

            {% block content %}{% endblock %}

            {% block pagination %}
                {% include "includes/pagination.html" %}
            {% endblock %}

        </div>
    </div>
</div>
</body>

</html>

templates/includes/pagination.html
{% if is_paginated %}
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item">
        <a href="?page= {{ page_obj.previous_page_number }}" class="page-link">prev</a>
      </li>
    {% endif %}
    <li class="page-item active">
      <span class="page-link">{{ page_obj.number }} of {{ paginator.num_pages }}</span>
    </li>
    {% if page_obj.has_next %}
      <li class="page-item">
        <a href="?page= {{ page_obj.next_page_number }}" class="page-link">next</a>
      </li>
    {% endif %}
  </ul>
{% endif %}

templates/includes/sidebar.html
<ul class="sidebar-nav list-group">
  {% if user.is_authenticated %}
    <li class="list-group-item">
      User: {{ user.username }}
    </li>
    <form action="{% url 'logout' %}" method="post">
      {% csrf_token %}
      <button type="submit">Log out</button>
    </form>
  {% else %}
    <li class="list-group-item">
      <a href="{% url 'login' %}">Login</a>
    </li>
  {% endif %}

   <br>

  <li class="list-group-item"><a href="{% url 'todo_servise:todo-list' %}">Home</a></li>
  <li class="list-group-item"><a href="{% url 'todo_servise:tag-list' %}">Tags</a></li>

{#  <li class="list-group-item"><a href="{% url 'taxi:index' %}">Home</a></li>#}
{#  <li class="list-group-item"><a href="{% url 'taxi:driver-list' %}">All drivers</a></li>#}
{#  <li class="list-group-item"><a href="{% url 'taxi:car-list' %}">All cars</a></li>#}
{#  <li class="list-group-item"><a href="{% url 'taxi:manufacturer-list' %}">All manufacturers</a></li>#}
</ul>

templates/todo_servise/tag_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete tag?</h1>
  <form action="" method="post">
    {% csrf_token %}
    <input type="submit" value="Yes" class="btn btn-danger">
  </form>
{% endblock %}

templates/todo_servise/tag_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} tag </h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/todo_servise/tag_list.html
{% extends "base.html" %}

{% block content %}
  <h1>
    Tags
    <a href="{% url 'todo_servise:tag-create' %}" class="btn btn-primary link-to-page">
      Add
    </a>
  </h1>

  {% if tag_list %}
    <table class="table">
      <tr>
        <th>Name</th>
        <th>Update</th>
        <th>Delete</th>
      </tr>

      {% for tag in tag_list %}
        <tr>
          <td>
              {{ tag.name }}
          </td>
          <td>
            <a class="btn btn-secondary"
               href="{% url 'todo_servise:tag-update' pk=tag.id %}">
              Update
            </a>
          </td>
          <td>
            <a class="btn btn-secondary"
               href="{% url 'todo_servise:tag-delete' pk=tag.id %}">
              Delete
            </a>
          </td>
        </tr>
      {% endfor %}
    </table>

  {% else %}
      <p>There are no tags in the service.</p>
  {% endif %}
{% endblock %}

templates/todo_servise/task_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete task?</h1>
  <form action="" method="post">
    {% csrf_token %}
    <input type="submit" value="Yes" class="btn btn-danger">
  </form>
{% endblock %}

templates/todo_servise/task_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} task </h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/todo_servise/todo_list.html
{% extends "base.html" %}

{% block content %}
  <h1>
    TODO list
    <a href="{% url 'todo_servise:task-created' %}" class="btn btn-primary link-to-page">
      Add task
    </a>
  </h1>
  
  {% if task_list %}
    {% for task in task_list %}
      <div>
        <h4>
          {{ task.content }} 
          {% if task.done %}
            Done 
            <a href="{% url 'todo_servise:task-done-or-not' pk=task.id %}" class="btn btn-secondary link-to-page">
              Undo
            </a>
          {% else %}
            Not done
            <a href="{% url 'todo_servise:task-done-or-not' pk=task.id %}" class="btn btn-success link-to-page">
              Complete
            </a>
          {% endif %}
        </h4>
        <p>
          Created: {{ task.datetime }}
          {% if task.ded_line%}
            Dead line: {{ task.ded_line }}
          {% endif %}
        </p>
        <p>
          Tags: 
          {% for tag in task.tags.all %}
            {{ tag }} 
          {% endfor %}
          <a href="{% url 'todo_servise:task-update' pk=task.pk%}">
            Update
          </a>
          <a href="{% url 'todo_servise:task-delete' pk=task.pk%}">
            Delete
          </a>
        </p>
      </div>
    {% endfor %}
  {% else %}
    <h5>
      List have no tasks
    </h5>
  {% endif %}
{% endblock %}